# Generated by Django 3.0.5 on 2020-04-25 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.BotUser')),
            ],
        ),
        migrations.CreateModel(
            name='MessageEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('LY', 'Lyrics'), ('CO', 'Command'), ('FA', 'Favorite')], default='LY', max_length=2)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.BotUser')),
            ],
        ),
    ]
