# Generated by Django 3.0.5 on 2020-04-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_messageevent_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='MxmTrack',
            fields=[
                ('commontrack_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('track_name', models.TextField()),
                ('artist_name', models.TextField()),
                ('vanity_id', models.TextField()),
                ('album_id', models.PositiveIntegerField()),
                ('album_name', models.TextField()),
                ('artist_id', models.PositiveIntegerField()),
                ('image_url', models.URLField(max_length=500, null=True)),
                ('track_url', models.URLField(default='https://www.musixmatch.com/', max_length=500)),
            ],
        ),
    ]
