"""
Django settings for m3bot project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import datetime

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-w*@m3nx%+(c#^1bo@y(#7$1mryj3ikdoqzxu1=6t)v815-+v!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bot'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'm3bot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'm3bot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

VERIFY_TOKEN= '4^_qs?Nx$:XsaY;8'

COMMAND_IDENTIFIER = '/'
COMMAND_INDEX_AT = 0

MESSAGE_HOOK = 'message'
POSTBACK_HOOK = 'postback'
SUPPORTED_FB_HOOKS = [MESSAGE_HOOK, POSTBACK_HOOK]

SESSION_TIME_THRESHOLD = datetime.timedelta(minutes=10)

DEFAULT_RECORDS_SIZE = 10

MUSIXMATCH_KEY = '47b674f3a0dd4389fa4cce1c9f629f39'
MUSIXMATCH_ENTRY = "https://api.musixmatch.com/ws/1.1/"

PAGE_TOKEN = 'EAAIfovoTi5UBACkhAfv72or2uu0hcRMuOPc6NKR9qBGwDF8k9MUxtYMdHcYdcRhKrOdqxCNIFoRLZALZCQMwIzelwE735UAu7tB18YIVam7j7L013ZAVH6AwitS40GIP1OMzKT3s7XshSfOPwcJu2kx6mQ7LBsL1EKjGWIADAZDZD'
FACEBOOK_GRAPH = 'https://graph.facebook.com/v2.6/'
MESSAGES_ENTRY = FACEBOOK_GRAPH + 'me/messages'
FB_URL = MESSAGES_ENTRY + '?access_token=' + PAGE_TOKEN

SPOTIFY_CLIENT_ID = 'd1ca9c0d2afc4e3c9869e3bac41a2c24'
SPOTIFY_CLIENT_SECRET_ID = '4a2985ad9df0475697113dd2c078a449'